import { Inter } from 'next/font/google';
import React from 'react';
import './globals.css';
import Navbar from '@/components/navbar';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-background text-foreground`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange
				>
					<header className='w-screen h-24 bg-transparent flex justify-center items-center gap-4'>
						<Navbar />
					</header>
					<section className='w-screen h-[calc(100vh-6rem) overflow-y-auto'>
						{children}
					</section>
					<footer></footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
