import { Inter } from 'next/font/google';
import React from 'react';
import './globals.css';
import Navbar from './components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<header>
					<Navbar className='w-screen h-24 bg-gray-600' />
				</header>
				<div className='w-screen h-[calc(100vh-6rem)] bg-white'>
					{children}
				</div>

				<footer></footer>
			</body>
		</html>
	);
}
